Rails Recipe App
albertkantwi/recipe-app pull request #19
Opened 2023-11-30 15:16 UTC by albertkantwi

Within this pull request, we have incorporated the following modifications;

- Integrated Devise for user authentication.
- Implemented authorization using CanCanCan for controlling user access.
- Added models for User, Food, Inventory, InventoryFood, Recipe, and RecipeFood.
- Set up associations between models to represent relationships.
- Implemented controllers for managing foods, recipes, and inventories.
- Created views for displaying lists of foods, recipes, and inventories.
- Designed forms for adding new foods and recipes.
- Developed unit tests for models to ensure proper validations.
- Implemented request specs for controllers to verify route configurations.
- Styled views for a visually appealing user interface.
- Ensured mobile responsiveness for a seamless experience on various devices.
- Fixed linters' errors.

Kindly review for us.

2023-11-30 17:40 UTC, mukhammadrizooff requested changes
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- TEAM work ✔️ 
- No linter errors ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️
- Descriptive `README` file ✔️
- All Spec file's tests passed ✔️ 
![image](https://github.com/albertkantwi/recipe-app/assets/63915024/ff4b408d-4b8f-461f-9f44-47477eb80b01)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 17:40 UTC, mukhammadrizooff commented on app/views/devise/mailer/confirmation_instructions.html.erb
> +<p><%= link_to 'Confirm my account', confirmation_url(@resource, confirmation_token: @token) %></p>
- [ ] [REQUIRED] Good job so far! I appreciate what you have done but the email registered in the `"Login"` and `"Signup"` parts is not confirmed, if the registered email is not confirmed, it is not possible to go from the `"Login"` page to other pages. This does not allow you to see all the properties of this project, so please fix this error 🙏🏼 

![image](https://github.com/albertkantwi/recipe-app/assets/63915024/c8a22b4e-f25d-4219-89ae-fcc88fc1e6ab)

2023-11-30 19:30 UTC, aamirkhan2478 requested changes
Hi @albertkantwi & @pushkar1995, 

![](https://media3.giphy.com/media/RcZlXVml8oKtoGQeqe/giphy.gif?cid=ecf05e47cw5pjd1gapdzk1t3vp0n73caujoqxw3vkcu8ssng&rid=giphy.gif&ct=g)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-30 19:30 UTC, aamirkhan2478 commented on app/views/recipes/index.html.erb
- [ ] Make sure your Recipes page look like a wireframe but for now your Recipes page page is not look like wireframe check below :point_down: to check comparison between your design and wireframe

**Your Design**
![screencapture-localhost-3000-recipes-2023-12-01-00_19_14](https://github.com/albertkantwi/recipe-app/assets/45226848/43e156f9-56fa-4f56-9842-a136815ff6de)

**Wireframe**
![wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/recipe-app/images/recipe_index.png?token=GHSAT0AAAAAACKVUSJ723IYB4Z2EA3VDYLCZLI5WPQ)

2023-11-30 19:30 UTC, aamirkhan2478 commented on app/views/recipes/public_recipies.html.erb
- [ ] Make sure your Public Recipes page looks like a wireframe but for now, your Public Recipes page page does not look like a wireframe check below 👇 to check the comparison between your design and wireframe

**Your Design**
![screencapture-localhost-3000-public-recipies-2023-12-01-00_21_05](https://github.com/albertkantwi/recipe-app/assets/45226848/eab89713-e647-4755-ac36-abc6fb00fe5c)

**Wireframe**
![Wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/recipe-app/images/public_recipe_index.png?token=GHSAT0AAAAAACKVUSJ7QRPBQZGDNM4YEKIEZLI52QQ)

2023-11-30 19:30 UTC, aamirkhan2478 commented on app/views/recipes/show.html.erb
- [ ] Make sure your Recipes Details page looks like a wireframe but for now, your Recipes Details page page does not look like a wireframe check below 👇 to check the comparison between your design and wireframe

**Your Design**
![screencapture-localhost-3000-recipes-1-2023-12-01-00_25_41](https://github.com/albertkantwi/recipe-app/assets/45226848/98e22432-aa61-4013-a879-11493a56e31d)

**Wireframe**
![wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/recipe-app/images/recipe_food.png?token=GHSAT0AAAAAACKVUSJ7XIFSESHVZAAGBIHKZLI555Q)

2023-11-30 19:30 UTC, aamirkhan2478 commented on app/views/shopping_list/index.html.erb
- [ ] Make sure your Public Recipes page looks like a wireframe but for now, your Public Recipes page page does not look like a wireframe check below 👇 to check the comparison between your design and wireframe

**Your Design**
![screencapture-localhost-3000-shopping-list-2023-12-01-00_28_10](https://github.com/albertkantwi/recipe-app/assets/45226848/2a9065e6-0e5d-4e9d-916e-f0600892db57)

**Wireframe**
![wireframe](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/recipe-app/images/inventory_shopping_list.png?token=GHSAT0AAAAAACKVUSJ7EYSQUPHXPU7CDPX2ZLI6APQ)

2023-12-02 06:15 UTC, rloterh commented on Gemfile
> +gem 'bootstrap', '~> 4.0'
Working properly! ✔️

2023-12-02 06:24 UTC, rloterh commented on app/views/recipes/index.html.erb
Resolved, but can be improved further. Let's ensure to add adequate spacing around the elements in this page, as seen in the design [template](https://raw.githubusercontent.com/microverseinc/curriculum-rails/main/recipe-app/images/recipe_index.png?token=GHSAT0AAAAAACFSKGIJHITG747ALQK4U4GGZLK3KPQ)

2023-12-02 06:27 UTC, rloterh commented on app/views/recipes/public_recipies.html.erb
Properly resolved! ✔️

2023-12-02 06:29 UTC, rloterh commented on app/views/recipes/show.html.erb
Properly resolved! ✔️

2023-12-02 06:29 UTC, rloterh commented on app/views/shopping_list/index.html.erb
Properly resolved! ✔️

2023-12-02 06:36 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Albert & Pushka,  

**RoR group project** is complete! 🏁 Good job! 👏 👏  Congratulations!  🎉🌟 

## Highlights 🎯 
🎲 Authentication with Devise gem properly implemented!
🎲 App schema closely follows given ERD!
🎲 Only particular owners can delete contents added by himself/herself!
🎲 All users can view public recipes!

## Optional suggestions 🧰 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Let's make the ReadMe stand out even better by including instructions under the _Getting Started_ section, on how to run the app, for instance, using the command `rails server`.


Keep being awesome! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 13:30 UTC, merged